config/routes.rb
NutriendoChubutAlumnos::Application.routes.draw do
  resources :regions

  resources :escuelas

  resources :obra_socials

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :diagnosticos

  resources :hospitals

  resources :telefonos

  resources :tipo_de_telefonos

  resources :localidads

  resources :domicilios

  resources :sexos

  resources :alumnos

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  attr_accessible :region_id, :escuela_id, :apellidos, :documento, :fecha_de_nacimiento, :nombres, :obra_social_id, :sexo_id, :diagnostico_attributes, :telefono_attributes, :domicilio_attributes
  
  validates :documento, :presence => true
  validates :documento, :uniqueness => true
  validates :documento, :numericality => true
  validates :apellidos, :presence => true
  validates :nombres, :presence => true
  validates :obra_social_id, :presence => true
  validates :sexo_id, :presence => true
  
  belongs_to :escuela
  belongs_to :region
  belongs_to :sexo
  belongs_to :obra_social
  # has_many a la clase diagnostico :dependent => :destroy para poder eliminar las clases dependientes en caso de borrar la persona
  has_many :diagnostico, :dependent => :destroy
  # :allow_destroy => true para poder borrar a traves del formulario 
  accepts_nested_attributes_for :diagnostico, :allow_destroy => true
  
  has_many :telefono, :dependent => :destroy
  accepts_nested_attributes_for :telefono, :allow_destroy => true
  
  has_many :domicilio, :dependent => :destroy
  accepts_nested_attributes_for :domicilio, :allow_destroy => true
  
  def to_s
    self.apellidos + ", " +  self.nombres + ", DNI: " + self.documento.to_s
  end
  
  def edad
    age = Date.today.year - self.fecha_de_nacimiento.year
    age -= 1 if Date.today < self.fecha_de_nacimiento + age.years #for days before birthday
    return age
  end
  def cant_diagnosticos
    self.diagnostico.count
  end
  
end

app/models/diagnostico.rb
class Diagnostico < ActiveRecord::Base
  attr_accessible :alumno_id, :biopsia, :fecha_de_diagnostico, :hospital_id, :observacion
  validates :alumno_id, :presence => true
  validates :hospital_id, :presence => true
  validates :fecha_de_diagnostico, :presence => true
  
  belongs_to :hospital
  belongs_to :alumno
  def to_s
    "Hopital: "+ self.hospital.to_s + " Fecha: " + self.fecha_de_diagnostico.to_s + " - " + self.observacion 
  end
end

app/models/domicilio.rb
class Domicilio < ActiveRecord::Base
  attr_accessible :calle, :dpto, :localidad_id, :numero, :piso, :alumno_id
  validates :calle, :presence => true
  validates :localidad_id, :presence => true
  validates :alumno_id, :presence => true
  belongs_to :alumno
  belongs_to :localidad
  def to_s
    self.localidad.to_s + " - Calle: " + self.calle.to_s + " Nro: " + self.numero.to_s + " " + self.piso.to_s + " " + self.dpto.to_s
  end
end

app/models/escuela.rb
class Escuela < ActiveRecord::Base
  attr_accessible :nombre, :numero
  
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  validates :numero, :presence => true
  validates :numero, :uniqueness => true
  validates :numero, :numericality => true
  has_many :alumno
  def to_s
    self.numero.to_s + " " + self.nombre
  end
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  attr_accessible :localidad_id, :nombre
  validates :localidad_id, :presence => true
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  belongs_to :localidad
  has_many :diagnostico
  def to_s
    if self.localidad_id then
       self.nombre #+' - ' + Localidad.find(self.localidad_id).nombre
    else
       self.nombre
    end 
  end
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :domicilio
  has_many :hospital
  def to_s
    self.nombre
  end
end

app/models/obra_social.rb
class ObraSocial < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :alumno
  def to_s
    self.nombre
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :alumno
  def to_s
    self.nombre
  end
end

app/models/sexo.rb
class Sexo < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :alumno
  def to_s
    self.nombre
  end
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
  attr_accessible :codigo_de_area, :numero, :tipo_de_telefono_id, :alumno_id
  validates :numero, :presence => true
  validates :codigo_de_area, :numericality => true
  validates :tipo_de_telefono_id, :presence => true
  validates :numero, :numericality => true
  belongs_to :tipo_de_telefono
  belongs_to :alumno
  def to_s
    self.tipo_de_telefono.to_s + " - " + self.codigo_de_area.to_s + " " + self.numero.to_s 
  end
end

app/models/tipo_de_telefono.rb
class TipoDeTelefono < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :telefono
  def to_s
    self.nombre
  end
end

app/controllers/domicilios_controller.rb
class DomiciliosController < InheritedResources::Base
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnosticos_helper.rb
module DiagnosticosHelper
end

app/helpers/domicilios_helper.rb
module DomiciliosHelper
end

app/helpers/escuelas_helper.rb
module EscuelasHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sexos_helper.rb
module SexosHelper
end

app/helpers/telefonos_helper.rb
module TelefonosHelper
end

app/views/domicilios/_form.html.erb
<%= form_for(@domicilio) do |f| %>
  <% if @domicilio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domicilio.errors.count, "error") %> prohibited this domicilio from being saved:</h2>

      <ul>
      <% @domicilio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :localidad_id %><br />
    <%= f.number_field :localidad_id %>
  </div>
  <div class="field">
    <%= f.label :calle %><br />
    <%= f.text_field :calle %>
  </div>
  <div class="field">
    <%= f.label :numero %><br />
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :piso %><br />
    <%= f.number_field :piso %>
  </div>
  <div class="field">
    <%= f.label :dpto %><br />
    <%= f.text_field :dpto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domicilios/edit.html.erb
<h1>Editing domicilio</h1>

<%= render 'form' %>

<%= link_to 'Show', @domicilio %> |
<%= link_to 'Back', domicilios_path %>

app/views/domicilios/index.html.erb
<h1>Listing domicilios</h1>

<table>
  <tr>
    <th>Localidad</th>
    <th>Calle</th>
    <th>Numero</th>
    <th>Piso</th>
    <th>Dpto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @domicilios.each do |domicilio| %>
  <tr>
    <td><%= domicilio.localidad_id %></td>
    <td><%= domicilio.calle %></td>
    <td><%= domicilio.numero %></td>
    <td><%= domicilio.piso %></td>
    <td><%= domicilio.dpto %></td>
    <td><%= link_to 'Show', domicilio %></td>
    <td><%= link_to 'Edit', edit_domicilio_path(domicilio) %></td>
    <td><%= link_to 'Destroy', domicilio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Domicilio', new_domicilio_path %>

app/views/domicilios/new.html.erb
<h1>New domicilio</h1>

<%= render 'form' %>

<%= link_to 'Back', domicilios_path %>

app/views/domicilios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Localidad:</b>
  <%= @domicilio.localidad_id %>
</p>

<p>
  <b>Calle:</b>
  <%= @domicilio.calle %>
</p>

<p>
  <b>Numero:</b>
  <%= @domicilio.numero %>
</p>

<p>
  <b>Piso:</b>
  <%= @domicilio.piso %>
</p>

<p>
  <b>Dpto:</b>
  <%= @domicilio.dpto %>
</p>


<%= link_to 'Edit', edit_domicilio_path(@domicilio) %> |
<%= link_to 'Back', domicilios_path %>