config/routes.rb
NutriendoChubutAlumnos::Application.routes.draw do
  resources :regions

  resources :escuelas

  resources :obra_socials

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :diagnosticos

  resources :hospitals

  resources :telefonos

  resources :tipo_de_telefonos

  resources :localidads

  resources :domicilios

  resources :sexos

  resources :alumnos

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  attr_accessible :region_id, :escuela_id, :apellidos, :documento, :fecha_de_nacimiento, :nombres, :obra_social_id, :sexo_id, :diagnostico_attributes, :telefono_attributes, :domicilio_attributes
  
  validates :documento, :presence => true
  validates :documento, :uniqueness => true
  validates :documento, :numericality => true
  validates :apellidos, :presence => true
  validates :nombres, :presence => true
  validates :obra_social_id, :presence => true
  validates :sexo_id, :presence => true
  
  belongs_to :escuela
  belongs_to :region
  belongs_to :sexo
  belongs_to :obra_social
  # has_many a la clase diagnostico :dependent => :destroy para poder eliminar las clases dependientes en caso de borrar la persona
  has_many :diagnostico, :dependent => :destroy
  # :allow_destroy => true para poder borrar a traves del formulario 
  accepts_nested_attributes_for :diagnostico, :allow_destroy => true
  
  has_many :telefono, :dependent => :destroy
  accepts_nested_attributes_for :telefono, :allow_destroy => true
  
  has_many :domicilio, :dependent => :destroy
  accepts_nested_attributes_for :domicilio, :allow_destroy => true
  
  def to_s
    self.apellidos + ", " +  self.nombres + ", DNI: " + self.documento.to_s
  end
  
  def edad
    age = Date.today.year - self.fecha_de_nacimiento.year
    age -= 1 if Date.today < self.fecha_de_nacimiento + age.years #for days before birthday
    return age
  end
  def cant_diagnosticos
    self.diagnostico.count
  end
  
end

app/models/diagnostico.rb
class Diagnostico < ActiveRecord::Base
  attr_accessible :alumno_id, :biopsia, :fecha_de_diagnostico, :hospital_id, :observacion
  validates :alumno_id, :presence => true
  validates :hospital_id, :presence => true
  validates :fecha_de_diagnostico, :presence => true
  
  belongs_to :hospital
  belongs_to :alumno
  def to_s
    "Hopital: "+ self.hospital.to_s + " Fecha: " + self.fecha_de_diagnostico.to_s + " - " + self.observacion 
  end
end

app/models/domicilio.rb
class Domicilio < ActiveRecord::Base
  attr_accessible :calle, :dpto, :localidad_id, :numero, :piso, :alumno_id
  validates :calle, :presence => true
  validates :localidad_id, :presence => true
  validates :alumno_id, :presence => true
  belongs_to :alumno
  belongs_to :localidad
  def to_s
    self.localidad.to_s + " - Calle: " + self.calle.to_s + " Nro: " + self.numero.to_s + " " + self.piso.to_s + " " + self.dpto.to_s
  end
end

app/models/escuela.rb
class Escuela < ActiveRecord::Base
  attr_accessible :nombre, :numero
  
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  validates :numero, :presence => true
  validates :numero, :uniqueness => true
  validates :numero, :numericality => true
  has_many :alumno
  def to_s
    self.numero.to_s + " " + self.nombre
  end
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  attr_accessible :localidad_id, :nombre
  validates :localidad_id, :presence => true
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  belongs_to :localidad
  has_many :diagnostico
  def to_s
    if self.localidad_id then
       self.nombre #+' - ' + Localidad.find(self.localidad_id).nombre
    else
       self.nombre
    end 
  end
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :domicilio
  has_many :hospital
  def to_s
    self.nombre
  end
end

app/models/obra_social.rb
class ObraSocial < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :alumno
  def to_s
    self.nombre
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :alumno
  def to_s
    self.nombre
  end
end

app/models/sexo.rb
class Sexo < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :alumno
  def to_s
    self.nombre
  end
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
  attr_accessible :codigo_de_area, :numero, :tipo_de_telefono_id, :alumno_id
  validates :numero, :presence => true
  validates :codigo_de_area, :numericality => true
  validates :tipo_de_telefono_id, :presence => true
  validates :numero, :numericality => true
  belongs_to :tipo_de_telefono
  belongs_to :alumno
  def to_s
    self.tipo_de_telefono.to_s + " - " + self.codigo_de_area.to_s + " " + self.numero.to_s 
  end
end

app/models/tipo_de_telefono.rb
class TipoDeTelefono < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :telefono
  def to_s
    self.nombre
  end
end

app/controllers/tipo_de_telefonos_controller.rb
class TipoDeTelefonosController < InheritedResources::Base
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domicilios_helper.rb
module DomiciliosHelper
end

app/helpers/escuelas_helper.rb
module EscuelasHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sexos_helper.rb
module SexosHelper
end

app/helpers/telefonos_helper.rb
module TelefonosHelper
end

app/helpers/tipo_de_telefonos_helper.rb
module TipoDeTelefonosHelper
end

app/views/tipo_de_telefonos/_form.html.erb
<%= form_for(@tipo_de_telefono) do |f| %>
  <% if @tipo_de_telefono.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_de_telefono.errors.count, "error") %> prohibited this tipo_de_telefono from being saved:</h2>

      <ul>
      <% @tipo_de_telefono.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_de_telefonos/edit.html.erb
<h1>Editing tipo_de_telefono</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_de_telefono %> |
<%= link_to 'Back', tipo_de_telefonos_path %>

app/views/tipo_de_telefonos/index.html.erb
<h1>Listing tipo_de_telefonos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipo_de_telefonos.each do |tipo_de_telefono| %>
  <tr>
    <td><%= tipo_de_telefono.nombre %></td>
    <td><%= link_to 'Show', tipo_de_telefono %></td>
    <td><%= link_to 'Edit', edit_tipo_de_telefono_path(tipo_de_telefono) %></td>
    <td><%= link_to 'Destroy', tipo_de_telefono, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tipo de telefono', new_tipo_de_telefono_path %>

app/views/tipo_de_telefonos/new.html.erb
<h1>New tipo_de_telefono</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_de_telefonos_path %>

app/views/tipo_de_telefonos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @tipo_de_telefono.nombre %>
</p>


<%= link_to 'Edit', edit_tipo_de_telefono_path(@tipo_de_telefono) %> |
<%= link_to 'Back', tipo_de_telefonos_path %>